language: ruby
cache: bundler_args: --without deployment # caching to speed up dependency installation
rvm:
- 2.4.1
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
script:
- echo "Starting build!"
